version: "1.0"
stages:
  - prepare
  - apply
  - install
steps:
  main_clone:
    title: Cloning repository
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: prepare
  auth:
    image: alpine:3.12
    title: Creating account.json
    stage: prepare
    commands:
      - echo $ACCOUNT_JSON_CONTENT > account.json
  init:
    image: hashicorp/terraform:0.13.0
    title: Initializing Terraform
    stage: apply
    commands:
      - terraform init
  plan:
    image: hashicorp/terraform:0.13.0
    title: Outputting Terraform plan
    stage: apply
    commands:
      - terraform plan
  apply:
    image: hashicorp/terraform:0.13.0
    title: Applying Terraform
    stage: apply
    commands:
      - terraform apply -auto-approve 
    when:
      branch:
        only:
          - master
  config:
    image: hashicorp/terraform:0.13.0
    title: Creating Kube Config
    stage: install
    commands:
      - cf_export CLUSTER_NAME=$(terraform output cluster_name)
      - cf_export PROJECT=$(terraform output project_id)
      - cf_export REGION=$(terraform output region)
      - cf_export KUBECONFIG=$PWD/kubeconfig
      - echo $KUBECONFIG
      - echo "gcloud container clusters get-credentials $CLUSTER_NAME --project $PROJECT --region $REGION"
