version: "1.0"
stages:
  - prepare
  - apply
steps:
  main_clone:
    title: Cloning repository
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: prepare
  auth:
    image: alpine:3.12
    title: Creating account.json
    stage: prepare
    commands:
      - echo $ACCOUNT_JSON_CONTENT > account.json
  create:
    image: hashicorp/terraform:0.13.0
    title: Deploying Terraform plan
    stage: apply
    commands:
      - terraform init
      - terraform apply -auto-approve 
